/**
 * Vitest global setup — loads TEST registry keys before any test runs.
 *
 * The published SDK ships with PRODUCTION keys (registry.aria.bar).
 * Tests use fixtures signed with ephemeral TEST keys generated by
 * scripts/generate-fixtures.ts and stored in test/fixtures/registry-keys.json.
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { setRegistryKeys } from '../src/registry-key';

const keysPath = join(import.meta.dirname, 'fixtures', 'registry-keys.json');
const keys = JSON.parse(readFileSync(keysPath, 'utf-8'));

function hexToBytes(hex: string): Uint8Array {
  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < hex.length; i += 2) {
    bytes[i / 2] = parseInt(hex.substring(i, i + 2), 16);
  }
  return bytes;
}

setRegistryKeys(
  hexToBytes(keys.pqPublicKey),
  hexToBytes(keys.edPublicKey),
);
