import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ml_dsa65 } from '@noble/post-quantum/ml-dsa.js';
import { ed25519 } from '@noble/curves/ed25519.js';
import { sha256 } from '@noble/hashes/sha2.js';
import { bytesToHex } from '@noble/hashes/utils.js';
import { canonicalJson } from '../src/canonical-json';

const __dirname = import.meta.dirname ?? dirname(fileURLToPath(import.meta.url));
const FIXTURES_DIR = join(__dirname, '..', 'test', 'fixtures');
const REGISTRY_KEY_PATH = join(__dirname, '..', 'src', 'registry-key.ts');

function toHex(bytes: Uint8Array): string {
  return bytesToHex(bytes);
}

function main() {
  mkdirSync(FIXTURES_DIR, { recursive: true });

  console.log('Generating ML-DSA-65 keypair...');
  const pqKeys = ml_dsa65.keygen();

  console.log('Generating Ed25519 keypair...');
  const edPriv = ed25519.utils.randomSecretKey();
  const edPub = ed25519.getPublicKey(edPriv);

  // Save registry keys (for tests)
  const registryKeys = {
    pqPublicKey: toHex(pqKeys.publicKey),
    pqSecretKey: toHex(pqKeys.secretKey),
    edPublicKey: toHex(edPub),
    edSecretKey: toHex(edPriv),
  };

  writeFileSync(
    join(FIXTURES_DIR, 'registry-keys.json'),
    JSON.stringify(registryKeys, null, 2),
  );
  console.log('Saved registry-keys.json');

  // Update src/registry-key.ts with test keys
  const registryKeyTs = `// ─────────────────────────────────────────────────────────
// @aria-registry/verify — ARIA Registry Trust Anchor
// Part of the ARIA Protocol by TrustLayer Foundation
// https://aria.bar/docs/sdk
// ─────────────────────────────────────────────────────────
//
// AUTO-GENERATED by scripts/generate-fixtures.ts — DO NOT EDIT MANUALLY
// These are TEST KEYS for development/testing only.
// For production, replace with the real ARIA Registry keys.

/**
 * Convert a hexadecimal string to a \`Uint8Array\`.
 * @internal
 */
function hexToBytes(hex: string): Uint8Array {
  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < hex.length; i += 2) {
    bytes[i / 2] = parseInt(hex.substring(i, i + 2), 16);
  }
  return bytes;
}

/**
 * ML-DSA-65 (FIPS 204) public key of the ARIA Registry.
 * Used to verify the post-quantum signature on every AID.
 *
 * @remarks Can be overridden at runtime via {@link setRegistryKeys}
 * for custom registries or key rotation scenarios.
 */
export let REGISTRY_PUBLIC_KEY_MLDSA65: Uint8Array = hexToBytes('${toHex(pqKeys.publicKey)}');

/**
 * Ed25519 (RFC 8032) public key of the ARIA Registry.
 * Used to verify the classical signature on every AID.
 *
 * @remarks Can be overridden at runtime via {@link setRegistryKeys}
 * for custom registries or key rotation scenarios.
 */
export let REGISTRY_PUBLIC_KEY_ED25519: Uint8Array = hexToBytes('${toHex(edPub)}');

/**
 * Composite cryptographic suite identifier.
 * Both ML-DSA-65 and Ed25519 signatures must verify under this suite.
 */
export const COMPOSITE_SUITE = 'mldsa65-ed25519-2026';

/**
 * Override the embedded registry public keys at runtime.
 *
 * Use this for custom ARIA registries, key rotation scenarios,
 * or testing against a different signing authority.
 *
 * @param pqPublicKey - ML-DSA-65 public key as raw bytes
 * @param classicalPublicKey - Ed25519 public key as raw bytes (32 bytes)
 *
 * @example
 * \`\`\`typescript
 * import { setRegistryKeys } from '@aria-registry/verify';
 *
 * setRegistryKeys(myPqPublicKey, myEd25519PublicKey);
 * \`\`\`
 *
 * @since 0.1.0
 */
export function setRegistryKeys(pqPublicKey: Uint8Array, classicalPublicKey: Uint8Array): void {
  REGISTRY_PUBLIC_KEY_MLDSA65 = pqPublicKey;
  REGISTRY_PUBLIC_KEY_ED25519 = classicalPublicKey;
}
`;

  // NOTE: No longer overwrites src/registry-key.ts — production keys stay embedded.
  // Tests use test/setup.ts which calls setRegistryKeys() with keys from registry-keys.json.
  console.log('Test keys saved to registry-keys.json (src/registry-key.ts NOT overwritten — production keys preserved)');

  // Create a valid AID (W3C VC JSON-LD)
  const now = new Date();
  const oneYearLater = new Date(now);
  oneYearLater.setFullYear(oneYearLater.getFullYear() + 1);

  const validVc: Record<string, unknown> = {
    '@context': [
      'https://www.w3.org/ns/credentials/v2',
      'https://aria.bar/ns/v1',
    ],
    // ARIA 1.0: top-level id is the credential-instance URL (W3C VC 2.0 §4.4),
    // not the agent DID. The DID lives in credentialSubject.id below.
    id: 'https://api.aria.bar/v1/credentials/01906b8f-7c8a-7d12-8e3f-2a91b4c8f019',
    type: ['VerifiableCredential', 'AgentIdentityDocument'],
    issuer: 'did:aria:registry',
    validFrom: now.toISOString(),
    validUntil: oneYearLater.toISOString(),
    credentialSubject: {
      id: 'did:aria:example.com:test-agent',
      previousCredentialId: 'https://api.aria.bar/v1/credentials/01905f23-3a1b-7c95-9d6e-b8e72f5104a3',
      spec_version: '1.0',
      agentName: 'TestAgent',
      version: '1.0.0',
      principal: {
        name: 'Example Corp',
        domain: 'example.com',
        jurisdiction: 'US',
        type: 'organization',
        verificationStatus: 'registry-confirmed',
      },
      trustLevel: 'L2',
      scope: [
        'data:general:read',
        'data:general:write',
        'communication:email:send',
      ],
      hitlRequired: {
        financialTransactions: true,
        dataExport: true,
      },
    },
    credentialStatus: {
      id: 'https://api.aria.bar/v1/status/list/1#42',
      type: 'BitstringStatusListEntry',
      statusPurpose: 'revocation',
      statusListIndex: '42',
      statusListCredential: 'https://api.aria.bar/v1/status/list/1',
    },
  };

  // Sign the valid VC
  const vcWithoutProof = { ...validVc };
  const canonicalPayload = canonicalJson(vcWithoutProof);
  const payloadBytes = new TextEncoder().encode(canonicalPayload);

  console.log('Signing with ML-DSA-65...');
  const pqSig = ml_dsa65.sign(payloadBytes, pqKeys.secretKey);

  console.log('Signing with Ed25519...');
  const edSig = ed25519.sign(payloadBytes, edPriv);

  const contentHash = toHex(sha256(payloadBytes));

  const proof = {
    type: 'DataIntegrityProof',
    cryptosuite: 'mldsa65-ed25519-2026',
    created: now.toISOString(),
    verificationMethod: 'did:aria:registry#key-1',
    proofPurpose: 'assertionMethod',
    proofValuePq: toHex(pqSig),
    proofValueClassical: toHex(edSig),
    contentHash,
  };

  const signedVc = { ...validVc, proof };

  writeFileSync(
    join(FIXTURES_DIR, 'valid-aid.json'),
    JSON.stringify(signedVc, null, 2),
  );
  console.log('Saved valid-aid.json');

  // The shape the registry actually issues: one composite `proofValue`,
  // u32be(pq length) then the ML-DSA-65 signature then the Ed25519 one,
  // base64url, and the spec_version production declares until the cutover.
  // Everything above uses the separate-field form, which no issuer emits;
  // without this fixture the suite never exercises the branch that matters.
  const productionVc = {
    ...validVc,
    credentialSubject: { ...validVc.credentialSubject, spec_version: '1.2' },
  };
  const prodPayload = new TextEncoder().encode(canonicalJson(productionVc));
  const prodPq = ml_dsa65.sign(prodPayload, pqKeys.secretKey);
  const prodEd = ed25519.sign(prodPayload, edPriv);
  const composite = new Uint8Array(4 + prodPq.length + prodEd.length);
  new DataView(composite.buffer).setUint32(0, prodPq.length, false);
  composite.set(prodPq, 4);
  composite.set(prodEd, 4 + prodPq.length);
  const toBase64Url = (b: Uint8Array) =>
    Buffer.from(b).toString('base64').replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
  writeFileSync(
    join(FIXTURES_DIR, 'valid-aid-production-form.json'),
    JSON.stringify({
      ...productionVc,
      proof: {
        type: 'DataIntegrityProof',
        created: now.toISOString(),
        proofValue: toBase64Url(composite),
        cryptosuite: 'mldsa65-ed25519-2026',
        proofPurpose: 'assertionMethod',
        verificationMethod: 'did:aria:registry#key-1',
      },
    }, null, 2),
  );
  console.log('Saved valid-aid-production-form.json');

  // Create expired AID
  const yesterday = new Date(now);
  yesterday.setDate(yesterday.getDate() - 1);
  const twoDaysAgo = new Date(now);
  twoDaysAgo.setDate(twoDaysAgo.getDate() - 2);

  const expiredVc: Record<string, unknown> = {
    ...validVc,
    validFrom: twoDaysAgo.toISOString(),
    validUntil: yesterday.toISOString(),
  };

  // Re-sign the expired VC
  const expiredWithoutProof = { ...expiredVc };
  const expiredCanonical = canonicalJson(expiredWithoutProof);
  const expiredPayloadBytes = new TextEncoder().encode(expiredCanonical);
  const expiredPqSig = ml_dsa65.sign(expiredPayloadBytes, pqKeys.secretKey);
  const expiredEdSig = ed25519.sign(expiredPayloadBytes, edPriv);
  const expiredContentHash = toHex(sha256(expiredPayloadBytes));

  const expiredProof = {
    ...proof,
    proofValuePq: toHex(expiredPqSig),
    proofValueClassical: toHex(expiredEdSig),
    contentHash: expiredContentHash,
  };

  const expiredSignedVc = { ...expiredVc, proof: expiredProof };

  writeFileSync(
    join(FIXTURES_DIR, 'expired-aid.json'),
    JSON.stringify(expiredSignedVc, null, 2),
  );
  console.log('Saved expired-aid.json');

  // Create tampered signature AID (flip last byte of PQ signature)
  const tamperedPqSig = new Uint8Array(pqSig);
  tamperedPqSig[tamperedPqSig.length - 1] ^= 0xff;

  const tamperedProof = {
    ...proof,
    proofValuePq: toHex(tamperedPqSig),
  };

  const tamperedVc = { ...validVc, proof: tamperedProof };

  writeFileSync(
    join(FIXTURES_DIR, 'tampered-aid.json'),
    JSON.stringify(tamperedVc, null, 2),
  );
  console.log('Saved tampered-aid.json');

  // Create tampered content AID (add scope after signing)
  const tamperedContentVc = JSON.parse(JSON.stringify(signedVc)) as Record<string, unknown>;
  const tamperedSubject = tamperedContentVc.credentialSubject as Record<string, unknown>;
  (tamperedSubject.scope as string[]).push('financial:invoice:approve');

  writeFileSync(
    join(FIXTURES_DIR, 'tampered-content.json'),
    JSON.stringify(tamperedContentVc, null, 2),
  );
  console.log('Saved tampered-content.json');

  // Create missing fields AID (no agentName)
  const missingFieldsVc: Record<string, unknown> = {
    '@context': [
      'https://www.w3.org/ns/credentials/v2',
      'https://aria.bar/ns/v1',
    ],
    id: 'did:aria:example.com:incomplete-agent',
    type: ['VerifiableCredential', 'AgentIdentityDocument'],
    issuer: 'did:aria:registry',
    validFrom: now.toISOString(),
    validUntil: oneYearLater.toISOString(),
    credentialSubject: {
      id: 'did:aria:example.com:incomplete-agent',
      // agentName intentionally missing
      version: '1.0.0',
      principal: {
        name: 'Example Corp',
        domain: 'example.com',
        jurisdiction: 'US',
        type: 'organization',
      },
      trustLevel: 'L2',
      scope: ['data:general:read'],
      hitlRequired: null,
    },
    proof: {
      type: 'DataIntegrityProof',
      cryptosuite: 'mldsa65-ed25519-2026',
      proofValuePq: 'deadbeef',
      proofValueClassical: 'deadbeef',
    },
  };

  writeFileSync(
    join(FIXTURES_DIR, 'missing-fields.json'),
    JSON.stringify(missingFieldsVc, null, 2),
  );
  console.log('Saved missing-fields.json');

  // Create L0 AID without dnsAnchor (L0 has no DNS anchor)
  const l0Vc: Record<string, unknown> = {
    '@context': ['https://www.w3.org/ns/credentials/v2', 'https://aria.bar/ns/v1'],
    // ARIA 1.0: top-level id is the credential-instance URL.
    id: 'https://api.aria.bar/v1/credentials/01906f12-3b4c-7d56-8e9f-1a2b3c4d5e6f',
    type: ['VerifiableCredential', 'AgentIdentityDocument'],
    issuer: 'did:aria:registry',
    validFrom: now.toISOString(),
    validUntil: oneYearLater.toISOString(),
    credentialSubject: {
      id: 'did:aria:aria.bar:u-test:l0-agent',
      spec_version: '1.0',
      agentName: 'L0TestAgent',
      version: '1.0.0',
      principal: { name: 'Test Individual', jurisdiction: 'US', type: 'individual', verificationStatus: 'self-declared' },
      trustLevel: 'L0',
      scope: ['data:general:read'],
      hitlRequired: null,
      // No dnsAnchor — L0 has no DNS requirement
    },
    credentialStatus: {
      id: 'https://api.aria.bar/v1/status/list/1#99',
      type: 'BitstringStatusListEntry',
      statusPurpose: 'revocation',
      statusListIndex: '99',
      statusListCredential: 'https://api.aria.bar/v1/status/list/1',
    },
  };

  const l0Canonical = canonicalJson(l0Vc);
  const l0Bytes = new TextEncoder().encode(l0Canonical);
  const l0PqSig = ml_dsa65.sign(l0Bytes, pqKeys.secretKey);
  const l0EdSig = ed25519.sign(l0Bytes, edPriv);
  const l0Hash = toHex(sha256(l0Bytes));

  const l0Signed = {
    ...l0Vc,
    proof: {
      type: 'DataIntegrityProof',
      cryptosuite: 'mldsa65-ed25519-2026',
      created: now.toISOString(),
      verificationMethod: 'did:aria:registry#key-1',
      proofPurpose: 'assertionMethod',
      proofValuePq: toHex(l0PqSig),
      proofValueClassical: toHex(l0EdSig),
      contentHash: l0Hash,
    },
  };

  writeFileSync(join(FIXTURES_DIR, 'valid-aid-l0-no-dns.json'), JSON.stringify(l0Signed, null, 2));
  console.log('Saved valid-aid-l0-no-dns.json');

  // Backward-compat fixture — pre-cutover format (no spec_version, no principal.verificationStatus)
  const v15Vc: Record<string, unknown> = {
    '@context': ['https://www.w3.org/ns/credentials/v2', 'https://aria.bar/ns/v1'],
    id: 'did:aria:example.com:pre-cutover-agent',
    type: ['VerifiableCredential', 'AgentIdentityDocument'],
    issuer: 'did:aria:registry',
    validFrom: now.toISOString(),
    validUntil: oneYearLater.toISOString(),
    credentialSubject: {
      id: 'did:aria:example.com:pre-cutover-agent',
      // No spec_version, no principal.verificationStatus — pre-cutover format
      agentName: 'LegacyAgent',
      version: '1.0.0',
      principal: { name: 'Legacy Corp', domain: 'example.com', jurisdiction: 'US', type: 'organization' },
      trustLevel: 'L1',
      scope: ['data:general:read'],
      hitlRequired: null,
    },
    credentialStatus: {
      id: 'https://api.aria.bar/v1/status/list/1#50',
      type: 'BitstringStatusListEntry',
      statusPurpose: 'revocation',
      statusListIndex: '50',
      statusListCredential: 'https://api.aria.bar/v1/status/list/1',
    },
  };

  const v15Canonical = canonicalJson(v15Vc);
  const v15Bytes = new TextEncoder().encode(v15Canonical);
  const v15PqSig = ml_dsa65.sign(v15Bytes, pqKeys.secretKey);
  const v15EdSig = ed25519.sign(v15Bytes, edPriv);
  const v15Hash = toHex(sha256(v15Bytes));

  const v15Signed = {
    ...v15Vc,
    proof: {
      type: 'DataIntegrityProof',
      cryptosuite: 'mldsa65-ed25519-2026',
      created: now.toISOString(),
      verificationMethod: 'did:aria:registry#key-1',
      proofPurpose: 'assertionMethod',
      proofValuePq: toHex(v15PqSig),
      proofValueClassical: toHex(v15EdSig),
      contentHash: v15Hash,
    },
  };

  writeFileSync(join(FIXTURES_DIR, 'valid-aid-pre-cutover.json'), JSON.stringify(v15Signed, null, 2));
  console.log('Saved valid-aid-pre-cutover.json');

  console.log('\nAll fixtures generated successfully!');
}

main();
